---
# Ansible Galaxy requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.general
    version: ">=6.0.0"
    # Required for: modprobe, zypper, pacman modules

  - name: ansible.posix
    version: ">=1.5.0"
    # Required for: sysctl module
