name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure role with '...'
        2. Run playbook '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: ansible-version
    attributes:
      label: Ansible Version
      description: Output of `ansible --version`
      placeholder: "ansible [core 2.15.0]"
    validations:
      required: true

  - type: dropdown
    id: target-os
    attributes:
      label: Target OS
      description: What operating system are you deploying to?
      options:
        - Ubuntu 22.04
        - Ubuntu 24.04
        - Debian 11
        - Debian 12
        - Rocky Linux 8
        - Rocky Linux 9
        - AlmaLinux 8
        - AlmaLinux 9
        - RHEL 8
        - RHEL 9
        - openSUSE Leap 15
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: k3s-version
    attributes:
      label: K3s Version
      description: What K3s version are you trying to install?
      placeholder: "v1.28.3+k3s1 or stable"

  - type: dropdown
    id: role-mode
    attributes:
      label: Role Mode
      description: What mode is the role running in?
      options:
        - server (first master)
        - server (joining cluster)
        - agent
        - uninstall

  - type: textarea
    id: config
    attributes:
      label: Role Configuration
      description: Relevant role variables (sanitize any secrets!)
      render: yaml
      placeholder: |
        k3s_role: server
        k3s_cluster_init: true
        k3s_disable_components:
          - traefik

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant Ansible output or system logs
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have sanitized any sensitive information from my configuration
          required: true
