---
# Simple K3s Cluster (1 Server + Multiple Agents)
# Good for small production workloads
#
# Usage:
#   ansible-playbook k3s.cluster.site -i inventory/hosts.yml

all:
  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            k3s-server-1:
              ansible_host: 192.168.1.10
              # ansible_user: ubuntu

        k3s_agent:
          hosts:
            k3s-agent-1:
              ansible_host: 192.168.1.20
            k3s-agent-2:
              ansible_host: 192.168.1.21
            k3s-agent-3:
              ansible_host: 192.168.1.22

  vars:
    # Connection settings (uncomment and modify as needed)
    # ansible_user: ubuntu
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # ansible_become: true

    # K3s settings
    k3s_server_taint: true  # Don't schedule workloads on server
