---
# High Availability K3s Cluster (3 Servers + Multiple Agents)
# Recommended for production workloads
#
# Architecture:
#   - 3 control plane servers with embedded etcd
#   - Multiple worker agents
#   - Optional: Load balancer for API access (recommended)
#
# Usage:
#   ansible-playbook k3s.cluster.site -i inventory/hosts.yml

all:
  children:
    k3s_cluster:
      children:
        k3s_server:
          hosts:
            k3s-server-1:
              ansible_host: 192.168.1.10
            k3s-server-2:
              ansible_host: 192.168.1.11
            k3s-server-3:
              ansible_host: 192.168.1.12

        k3s_agent:
          hosts:
            k3s-agent-1:
              ansible_host: 192.168.1.20
            k3s-agent-2:
              ansible_host: 192.168.1.21
            k3s-agent-3:
              ansible_host: 192.168.1.22
            k3s-agent-4:
              ansible_host: 192.168.1.23

  vars:
    # Connection settings
    # ansible_user: ubuntu
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # ansible_become: true

    # K3s HA settings
    k3s_server_taint: true  # Don't schedule workloads on servers

    # TLS-SAN entries for API access
    # Include: load balancer IP/hostname, all server IPs, any DNS names
    k3s_server_tls_san:
      - "k3s-api.example.com"        # Load balancer DNS
      - "192.168.1.100"              # Load balancer IP
      - "192.168.1.10"               # Server 1
      - "192.168.1.11"               # Server 2
      - "192.168.1.12"               # Server 3

      # Optional: External load balancer for API (if you have one)
      # k3s_api_server_url: "https://k3s-api.example.com:6443"
